openapi: 3.1.0
info:
  title: Structures
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /structures:
    get:
      summary: Get structures
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Structure.yaml
        '401':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: getStructuresList
      description: Get an array of structures.
      parameters: []
      tags:
        - Structures
    post:
      summary: Create a structure
      operationId: CreateStructure
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/Structure.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      description: Create a new structure.
      tags:
        - Structures
    parameters: []
  '/structures/{structureID}':
    parameters:
      - schema:
          type: string
        name: structureID
        in: path
        required: true
    get:
      summary: Get a structure
      tags:
        - Structures
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Structure.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: getOneStructure
      description: Get a structure by ID.
      parameters: []
    patch:
      summary: Update a structure
      operationId: modifyOneStructure
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Structure.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      description: Modify a structure by ID.
      tags:
        - Structures
    delete:
      summary: Delete structure
      operationId: deleteOneStructure
      description: Delete a structure by ID.
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Structures
  '/structures/{structureID}/names':
    parameters:
      - schema:
          type: string
        name: structureID
        in: path
        required: true
    get:
      summary: Get a structure's name
      tags:
        - Names
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/StructureNames.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-structures-structureID-names
    post:
      summary: Create a structure's name
      operationId: post-structures-structureID-names
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/StructureNames.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/StructureNames.yaml
      tags:
        - Names
  '/structures/{structureID}/names/{nameID}':
    parameters:
      - schema:
          type: string
        name: structureID
        in: path
        required: true
      - schema:
          type: string
        name: nameID
        in: path
        required: true
    get:
      summary: Get a structure's name
      tags:
        - Names
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/StructureNames.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-structures-structureID-names-nameID
    patch:
      summary: Update a structure's name
      operationId: patch-structures-structureID-names-nameID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/StructureNames.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Names
    delete:
      summary: Delete a structure's name
      operationId: delete-structures-structureID-names-nameID
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Names
  '/structures/{structureID}/logos':
    parameters:
      - schema:
          type: string
        name: structureID
        in: path
        required: true
    get:
      summary: Get structure's logos
      tags:
        - Logos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Logo.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-structures-structureID-logos
    post:
      summary: Create a logo
      operationId: post-structures-structureID-logos
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/Logo.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/Logo.yaml
      tags:
        - Logos
  '/structures/{structureID}/logos/{logoID}':
    parameters:
      - schema:
          type: string
        name: structureID
        in: path
        required: true
      - schema:
          type: string
        name: logoID
        in: path
        required: true
    get:
      summary: Get a structure's logo
      tags:
        - Logos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Logo.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-structures-structureID-logos-logoID
    patch:
      summary: Update a structure's logo
      operationId: patch-structures-structureID-logos-logoID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Logo.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/Logo.yaml
      tags:
        - Logos
    delete:
      summary: Delete a structure's logo
      operationId: delete-structures-structureID-logos-logoID
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Logos
  '/structures/{structureID}/addresses':
    parameters:
      - schema:
          type: string
        name: structureID
        in: path
        required: true
    get:
      summary: Get structure's addresses
      tags: []
      responses: {}
      operationId: get-structures-structureID-addresses
components:
  schemas: {}
  parameters: {}
  examples: {}
  responses:
    Error:
      description: Error response.
      content:
        application/json:
          schema:
            $ref: ./models/Error.yaml
tags:
  - name: Addresses
  - name: Categories
  - name: Identifiers
  - name: Logos
  - name: Names
  - name: SocialMedias
  - name: Structures
  - name: Weblinks
