openapi: 3.0.0
info:
  title: Terms
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /terms:
    get:
      summary: Get terms
      tags:
        - Terms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/Term.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-terms
    post:
      summary: Create a Term
      operationId: post-terms
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/Term.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Terms
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/Term.yaml
  '/terms/{termID}':
    parameters:
      - schema:
          type: string
        name: termID
        in: path
        required: true
    get:
      summary: Get a term
      tags:
        - Terms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Term.yaml
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-terms-termID
    patch:
      summary: Update a term
      operationId: patch-terms-termID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Term.yaml
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Terms
    delete:
      summary: Delete a term
      operationId: delete-terms-termID
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - Terms
components:
  responses:
    Error:
      description: Example response
      content:
        application/json:
          schema:
            $ref: ./models/Error.yaml
tags:
  - name: Terms

