title: Projet
type: object
description: ''
properties:
  id:
    type: string
  nameFr:
    type: string
  nameEng:
    type: string
  fullNameFr:
    type: string
  fullNameEng:
    type: string
  acronymFr:
    type: string
  acronymEng:
    type: string
  description:
    type: string
  startDate:
    $ref: ./Date.yaml
  endDate:
    $ref: ./Date.yaml
  officialWebsite:
    $ref: ./Link.yaml
  localisations:
    type: array
    description: Localisation id
    items:
      $ref: ./Localisation.yaml
  webVisibility:
    type: array
    items:
      $ref: ./Link.yaml
  grantStructures:
    description: Structure id
    type: array
    items:
      $ref: ./Structure.yaml
  contact:
    $ref: ./Contact.yaml
  structures:
    type: array
    description: Structure id
    items:
      $ref: ./Structure.yaml
  grantPart:
    type: string
  internalDocumentIds:
    type: array
    description: InternalDocument id
    items:
      type: string
  followUp:
    type: array
    items:
      $ref: ./FollowUp.yaml
  newsCast:
    type: array
    items:
      $ref: ./PressRelease.yaml
  createdBy:
    type: string
    description: User id
  createdAt:
    type: string
    format: time
    readOnly: true
  updatedBy:
    type: string
    description: User id
  updatedAt:
    type: string
    format: time
    readOnly: true
required:
  - id
  - description
  - startDate
  - endDate
  - contact
  - createdBy
  - createdAt
