title: Projet
type: object
description: ''
properties:
  id:
    type: string
  nameFr:
    type: string
  nameEng:
    type: string
  fullNameFr:
    type: string
  fullNameEng:
    type: string
  acronymFr:
    type: string
  acronymEng:
    type: string
  description:
    type: string
  startDate:
    type: string
  endDate:
    type: string
  officialWebsite:
    type: string
  localisationId:
    type: array
    items:
      $ref: ./Localisation.yaml
  webVisibility:
    type: array
    items:
      $ref: ./Link.yaml
  grantStructureId:
    $ref: ./Structure.yaml
  contact:
    $ref: ./Contact.yaml
  structureId:
    type: array
    items:
      $ref: ./Structure.yaml
  grantPart:
    type: string
  documentId:
    type: array
    items:
      $ref: ./InternalDocument.yaml
  followUp:
    $ref: ./FollowUp.yaml
  newsCast:
    type: array
    items:
      $ref: ./PressRelease.yaml
  createdBy:
    $ref: ./User.yaml
  createdAt:
    type: string
  updatedBy:
    $ref: ./User.yaml
  updatedAt:
    type: string
required:
  - id
  - description
  - startDate
  - endDate
  - contact
  - createdBy
  - createdAt
