openapi: 3.0.1
info:
  title: Authentication.
  description: Authentication API.
  termsOfService: ''
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'https://paysage.staging.dataesr.ovh/api'
  - url: 'http://paysage.staging.dataesr.ovh/api'
paths:
  /auth/signin:
    post:
      summary: Sign a user in
      description: A signin route that returns a token that represent user info.
      requestBody:
        description: User credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userSignIn'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
        '500':
          description: ServerError
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
      operationId: signIn
  /auth/recover:
    post:
      summary: Send password recovery code
      description: Sends an email with a token to recover user's password
      requestBody:
        description: Required user email for sending the recover-password link
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
        required: true
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
        '500':
          description: ServerError
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
      operationId: sendPassordRecoveryCode
    parameters: []
    get:
      summary: Reset password
      operationId: recoverPassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/message'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: User's secret code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userEmail'
  /auth/:
    post:
      summary: Ask for resending an account confirmation email
      description: Send an email with a token to confirm user's account
      requestBody:
        description: Required user email for sending the activate-account link
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userEmail'
        required: true
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/message'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
        '500':
          description: ServerError
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: User's secret code
      operationId: resendConfirmCode
    parameters: []
  /auth/signup:
    post:
      summary: Sign a user up
      description: Create a user account
      requestBody:
        description: Required user info for account creation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userSignUp'
        required: true
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/message'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
        '500':
          description: ServerError
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
      operationId: signUp
  /auth/activate:
    get:
      summary: Reads a token to confirm user's account
      parameters:
        - name: token
          in: path
          description: A token sent by email
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: query
          name: code
          description: User's secret code
      responses:
        '200':
          description: User account activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/message'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
        '500':
          description: ServerError
          content:
            application/json:
              schema:
                $ref: ../Structures/models/Error.yaml
      operationId: activateAccount
      description: Activate user account
    parameters: []
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        roles:
          type: integer
          description: User Status
          format: int32
      xml:
        name: User
    userSignIn:
      type: object
      properties:
        account:
          type: string
          example: folland87 or folland@dataesr.ovh
          description: Username or email address
        password:
          type: string
          example: password
      required:
        - account
        - password
    userSignUp:
      required:
        - email
        - password
        - username
      type: object
      properties:
        username:
          type: string
          example: folland87
        password:
          type: string
          example: password
        email:
          type: string
          example: folland@dataesr.ovh
