openapi: 3.0.0
info:
  title: commons.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
components:
  parameters:
    query:
      name: query
      in: query
      required: false
      schema:
        type: string
    skip:
      name: skip
      in: query
      required: false
      schema:
        type: integer
        format: int64
        minimum: 0
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int64
        default: 20
        minimum: 1
        maximum: 100
    project:
      name: project
      in: query
      required: false
      schema:
        type: string
      description: hashed projection object
  responses: {}
