type: object
title: Meta
additionalProperties: false
properties:
  createdAt:
    type: string
    format: date-time
  createdBy:
    type: string
  modifiedAt:
    type: string
    format: date-time
  modifiedBy:
    type: string
readOnly: true
